--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Psycofeu/hSoundUtils
build-by-default: true
branches:
- main
projects:
  hSoundUtils:
    path: ""
    model: virion
    type: library
...
